# Generated by Django 5.1.7 on 2025-04-01 07:32

import after.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('user', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('video', models.FileField(blank=True, null=True, upload_to='after/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), after.models.Items.file_limit], verbose_name='video')),
                ('img', models.ImageField(blank=True, null=True, upload_to='after/img/', verbose_name='img')),
                ('img_back_none', models.ImageField(blank=True, null=True, upload_to='after/img/', verbose_name='img_back_none')),
            ],
        ),
    ]
