# Generated by Django 5.1.7 on 2025-04-01 08:45

import after.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='video',
            field=models.FileField(null=True, upload_to='after/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), after.models.Items.file_limit], verbose_name='video'),
        ),
    ]
