# Generated by Django 5.1.7 on 2025-04-06 10:31

import after.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after', '0002_alter_items_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='pin',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='pin'),
        ),
        migrations.AlterField(
            model_name='items',
            name='user',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
    ]
