# Generated by Django 5.1.7 on 2025-04-06 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after', '0003_items_pin_alter_items_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='pin',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='pin'),
        ),
    ]
