# Generated by Django 5.1.7 on 2025-04-06 10:53

import after.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after', '0004_alter_items_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='pin',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='pin:必須'),
        ),
        migrations.AlterField(
            model_name='items',
            name='user',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email:任意'),
        ),
        migrations.AlterField(
            model_name='items',
            name='video',
            field=models.FileField(null=True, upload_to='after/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), after.models.Items.file_limit], verbose_name='video:必須'),
        ),
    ]
