# Generated by Django 5.2.1 on 2025-06-16 09:42

import after.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after', '0006_items_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='items',
            name='user',
        ),
        migrations.AddField(
            model_name='items',
            name='status',
            field=models.CharField(default='unstarted', max_length=20, verbose_name='進捗状況'),
        ),
        migrations.AlterField(
            model_name='items',
            name='pin',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='pin:4桁'),
        ),
        migrations.AlterField(
            model_name='items',
            name='video',
            field=models.FileField(null=True, upload_to='after/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), after.models.Items.file_limit], verbose_name='video'),
        ),
    ]
