# Generated by Django 5.2.1 on 2025-06-16 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after', '0007_remove_items_progress_remove_items_user_items_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='pin',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='PIN'),
        ),
    ]
